# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e5046057cfed15d636e8a9dea8c5959652b438ec8d13bb5369c92a7095881ce86affd050801d3abb113918858c4a145463e2d6386d9862b2396c8f32cfe17f2d

test:
  secret_key_base: 0900336afd05f4b620cb375e1e5ddd3ee2d7f7d38cd3c335f753eb112c33ef246ba7eb6d4b1b77518beaea9f387703ac6424fa00a36bff8cbe9aa5ae803869b1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
